# Generated by Django 5.2 on 2025-07-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cronograma_publico_alter_cronograma_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
