# Generated by Django 5.2 on 2025-07-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pessoa_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='pontos_custo',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='resgatada',
            field=models.BooleanField(default=False),
        ),
    ]
